---

- name: Include variables specific for the distribution.
  ansible.builtin.include_vars: "{{ item }}"
  with_items:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- ansible.builtin.import_tasks:
    file: install.yml
- ansible.builtin.import_tasks:
    file: configure.yml
